const newOrder = () => ({
  arrivalDate: "",
  brand: "",
  chargeMoney: "",
  chargePercent: "",
  color: "",
  country: 1,
  debt: "",
  gcCode: "",
  imgLink: "",
  inM: "",
  link: "",
  method: 0,
  note: "",
  offVal: 0,
  orderDate: new Date().toISOString().substr(0, 10),
  orderId: "",
  orderNumber: "",
  outM: "",
  price: "",
  quantity: 1,
  rate: "",
  shipWeb: "",
  shippingCharge: "",
  site: "",
  size: "",
  status: 1,
  surCharge: "",
  tax: "",
  total: "",
  totalCommission: "",
  totalin: "",
  transfered: "",
  userId: "",
  weight: 0,
  weightRate: 11.0
});

export default newOrder;
